### ISSUE TITLE
DatabaseManagerのclean実行時のエラー

### ISSUE THREAD

**Issue by tasuren** [RextTeam/rt-lib#1]
https://github.com/RextTeam/rt-bot/issues/155

**Comment by yaakiyu** [comment]
見てて気になったけども
エラーが出てる次の行のbotってどこから出てきたの?

**Comment by tasuren** [comment]
what

**Comment by yaakiyu** [comment]
次の行じゃないわ
https://github.com/RextTeam/rt-lib/blob/main/common/database.py#L91
これ

**Comment by tasuren** [comment]
わからぬ。
誰か治しといてくれ。
恐らく`tdpocket.bot`にすればいい。

**Comment by tasuren** [comment]
修正した。
